Comment: For standard recipes, only Identifier, CATEGORY, NAME, SELF_SERVICE_DESCRIPTION, ParentRecipe need to be changed.
Description: Creates all production policies for a particular title.
Identifier: com.github.grahampugh.recipes.jss-prod.prod-self-service
MinimumVersion: "2.3"

Input:
  NAME: ++OVERRIDE_OR_INSERT_SOFTWARE_NAME_HERE++
  CATEGORY: Applications
  PROD_NAME: "%NAME%"
  PROD_UPDATE_GROUP_NAME: "%NAME%-prod-update-smart"
  PROD_UPDATE_GROUP_TEMPLATE: SmartGroupTemplate-prod.xml
  PROD_UPDATE_POLICY_TEMPLATE: PolicyTemplate-prod-selfservice.xml
  SELF_SERVICE_DESCRIPTION: ++CHANGE DESCRIPTION++
  SELF_SERVICE_DISPLAY_NAME: "%NAME%"
  SELF_SERVICE_ICON: "%NAME%.png"
  SELF_SERVICE_INSTALL_BUTTON: Install %version%
  SELF_SERVICE_REINSTALL_BUTTON: Install %version%
  STOP_IF_NO_JSS_UPLOAD: false
  TRIGGERONLY_POLICY_CATEGORY: Triggered Installers
  TRIGGERONLY_POLICY_TEMPLATE: PolicyTemplate-prod-triggeronly.xml
  TRIGGER_NAME: "%NAME%-install"

Process:
  - Processor: com.github.grahampugh.recipes.commonprocessors/JSSRecipeReceiptChecker
    Arguments:
      name: "%NAME%"

  - Processor: JSSImporter
    Comment: Trigger-only policy
    Arguments:
      category: "%CATEGORY%"
      pkg_path: "%pkg_path%"
      policy_category: "%TRIGGERONLY_POLICY_CATEGORY%"
      policy_template: "%TRIGGERONLY_POLICY_TEMPLATE%"
      prod_name: "%PROD_NAME%"
      version: "%version%"

  - Processor: JSSImporter
    Comment: Self Service install policy
    Arguments:
      groups:
        - name: "%PROD_UPDATE_GROUP_NAME%"
          smart: true
          template_path: "%PROD_UPDATE_GROUP_TEMPLATE%"
      pkg_path: ""
      policy_category: "%CATEGORY%"
      policy_template: "%PROD_UPDATE_POLICY_TEMPLATE%"
      prod_name: "%PROD_NAME%"
      self_service_description: "%SELF_SERVICE_DESCRIPTION%"
      self_service_icon: "%SELF_SERVICE_ICON%"
      version: "%version%"
